version: "3.8"
services:
   watchtower: # Used to automatically update the easytier image, delete this part if not needed
         command: --interval 3600 --cleanup --label-enable
         container_name: watchtower
         environment:
               - WATCHTOWER_NO_STARTUP_MESSAGE
         image: containrrr/watchtower
         restart: always
         volumes:
               - /var/run/docker.sock:/var/run/docker.sock
   easytier:
         restart: always
         labels:
               com.centurylinklabs.watchtower.enable: "true"        
         privileged: true
         mem_limit: 0m
         container_name: easytier
         hostname: easytier
         network_mode: host
         volumes:
               - /etc/easytier:/root
         environment:
               - TZ=Asia/Shanghai
         image: easytier/easytier:latest
         command: --network-name 123 --network-secret 123
